export const data = [
  {
    name: 'Jennifer',
    img: './img/pets/jennifer.png',
    type: 'Dog',
    breed: 'Labrador',
    description:
      "Jennifer is a sweet 2 months old Labrador that is patiently waiting to find a new forever home. This girl really enjoys being able to go outside to run and play, but won't hesitate to play up a storm in the house if she has all of her favorite toys.",
    age: '2 months',
    inoculations: ['none'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Sophia',
    img: './img/pets/sophia.png',
    type: 'Dog',
    breed: 'Shih tzu',
    description:
      "Sophia here and I'm looking for my forever home to live out the best years of my life. I am full of energy. Everyday I'm learning new things, like how to walk on a leash, go potty outside, bark and play with toys and I still need some practice.",
    age: '1 month',
    inoculations: ['parvovirus'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Woody',
    img: './img/pets/woody.png',
    type: 'Dog',
    breed: 'Golden Retriever',
    description:
      'Woody is a handsome 3 1/2 year old boy. Woody does know basic commands and is a smart pup. Since he is on the stronger side, he will learn a lot from your training. Woody will be happier when he finds a new family that can spend a lot of time with him.',
    age: '3 years 6 months',
    inoculations: ['adenovirus', 'distemper'],
    diseases: ['right back leg mobility reduced'],
    parasites: ['none'],
  },
  {
    name: 'Scarlett',
    img: './img/pets/scarlett.png',
    type: 'Dog',
    breed: 'Jack Russell Terrier',
    description:
      'Scarlett is a happy, playful girl who will make you laugh and smile. She forms a bond quickly and will make a loyal companion and a wonderful family dog or a good companion for a single individual too since she likes to hang out and be with her human.',
    age: '3 months',
    inoculations: ['parainfluenza'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Katrine',
    img: './img/pets/katrine.png',
    type: 'Cat',
    breed: 'British Shorthair',
    description:
      'Katrine is a beautiful girl. She is as soft as the finest velvet with a thick lush fur. Will love you until the last breath she takes as long as you are the one. She is picky about her affection. She loves cuddles and to stretch into your hands for a deeper relaxations.',
    age: '6 months',
    inoculations: ['panleukopenia'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Timmy',
    img: './img/pets/timmy.png',
    type: 'Cat',
    breed: 'British Shorthair',
    description:
      'Timmy is an adorable grey british shorthair male. He loves to play and snuggle. He is neutered and up to date on age appropriate vaccinations. He can be chatty and enjoys being held. Timmy has a lot to say and wants a person to share his thoughts with.',
    age: '2 years 3 months',
    inoculations: ['calicivirus', 'viral rhinotracheitis'],
    diseases: ['kidney stones'],
    parasites: ['none'],
  },
  {
    name: 'Freddie',
    img: './img/pets/freddie.png',
    type: 'Cat',
    breed: 'British Shorthair',
    description:
      'Freddie is a little shy at first, but very sweet when he warms up. He likes playing with shoe strings and bottle caps. He is quick to learn the rhythms of his human’s daily life. Freddie has bounced around a lot in his life, and is looking to find his forever home.',
    age: '2 months',
    inoculations: ['rabies'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Charly',
    img: './img/pets/charly.png',
    type: 'Dog',
    breed: 'Jack Russell Terrier',
    description:
      'This cute boy, Charly, is three years old and he likes adults and kids. He isn’t fond of many other dogs, so he might do best in a single dog home. Charly has lots of energy, and loves to run and play. We think a fenced yard would make him very happy.',
    age: '8 years',
    inoculations: ['bordetella bronchiseptica', 'leptospirosis'],
    diseases: ['deafness', 'blindness'],
    parasites: ['lice', 'fleas'],
  },
  // =================================================
  {
    name: 'Teddy',
    img: './img/pets/teddy.png',
    type: 'Dog',
    breed: 'Golden Retriever',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis numquam dignissimos! Minus sequi dolorem voluptatibus aut in officiis, culpa ex quod dicta a doloremque',
    age: '2 years 7 months',
    inoculations: ['none'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Monty',
    img: './img/pets/monty.png',
    type: 'Dog',
    breed: 'Dachshund',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '1 month',
    inoculations: ['parvovirus'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Alfie',
    img: './img/pets/alfie.png',
    type: 'Dog',
    breed: 'Berner Sennenhund',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '3 months',
    inoculations: ['adenovirus', 'distemper'],
    diseases: ['right back leg mobility reduced'],
    parasites: ['none'],
  },
  {
    name: 'Bella',
    img: './img/pets/bella.png',
    type: 'Dog',
    breed: 'Collie',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '1 year 3 months',
    inoculations: ['parainfluenza'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Rosie',
    img: './img/pets/rosie.png',
    type: 'Cat',
    breed: 'American wire-haired',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '2 years 5 months',
    inoculations: ['panleukopenia'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Molly',
    img: './img/pets/molly.png',
    type: 'Cat',
    breed: 'British Longhair',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '1 year 3 months',
    inoculations: ['bordetella bronchiseptica', 'leptospirosis'],
    diseases: ['kidney stones'],
    parasites: ['none'],
  },
  {
    name: 'Loki',
    img: './img/pets/loki.png',
    type: 'Cat',
    breed: 'Maine Coon',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '9 months',
    inoculations: ['rabies'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Merlin',
    img: './img/pets/merlin.png',
    type: 'Dog',
    breed: 'Border collie',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '2 years 5 months',
    inoculations: ['bordetella bronchiseptica'],
    diseases: ['none'],
    parasites: ['fleas'],
  },
  {
    name: 'Murphy',
    img: './img/pets/murphy.png',
    type: 'Dog',
    breed: 'Long-haired dachshund',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '6 months',
    inoculations: ['none'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Ralph',
    img: './img/pets/ralph.png',
    type: 'Dog',
    breed: 'English cocker spaniel',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '1 year 1 month',
    inoculations: ['parvovirus'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Bonnie',
    img: './img/pets/bonnie.png',
    type: 'Dog',
    breed: 'Staffordshire Terrier',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '2 year 3 months',
    inoculations: ['adenovirus', 'distemper'],
    diseases: ['right back leg mobility reduced'],
    parasites: ['none'],
  },
  {
    name: 'Honey',
    img: './img/pets/honey.png',
    type: 'Cat',
    breed: 'Maine Coon',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '1 year 3 months',
    inoculations: ['parainfluenza'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Simba',
    img: './img/pets/simba.png',
    type: 'Cat',
    breed: 'American Shorthair',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '2 months',
    inoculations: ['panleukopenia'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Percy',
    img: './img/pets/percy.png',
    type: 'Cat',
    breed: 'British Shorthair',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '1 years 2 months',
    inoculations: ['calicivirus'],
    diseases: ['kidney stones'],
    parasites: ['none'],
  },
  {
    name: 'Rufus',
    img: './img/pets/rufus.png',
    type: 'Cat',
    breed: 'Scottish Shorthair',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '3 months',
    inoculations: ['rabies'],
    diseases: ['none'],
    parasites: ['none'],
  },
  {
    name: 'Maggie',
    img: './img/pets/maggie.png',
    type: 'Cat',
    breed: 'Abyssinian cat',
    description:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Neque explicabo impedit dolore animi quas consequuntur sed, quasi praesentium, quos, amet eveniet! Inventore dicta fugit tempore perferendis quo explicabo, assumenda possimus! Eos nihil perferendis incidunt omnis',
    age: '2 years',
    inoculations: ['leptospirosis'],
    diseases: ['deafness'],
    parasites: ['lice'],
  },
];
